### ISSUE TITLE
Mouse capture not working in HTML export

### ISSUE THREAD

**Issue by alt-romes** [Whimfoome/godot-FirstPersonStarter#10]
Hey! Firstly, thanks for the script/scene, it works really well on the scene editor.
However, when I export the game to Web/HTML5, the mouse camera rotation, and the mouse_mode_capture, stop working.

To recreate the error try exporting the game to web and rotate the camera.

Thanks,
Romes

**Comment by AlfaHound** [comment]
New to Godot, but can confirm the problem

**Comment by Whimfoome** [comment]
Fixed in c1b173aae9ee0930ad7d5d86b75eaaaff44820e3

**Comment by Whimfoome** [comment]
This change was reverted, please visit the [Wiki's FAQ](https://github.com/Whimfoome/godot-FirstPersonStarter/wiki/FAQ#q-why-my-mouse-doesnt-get-captured-on-webhtml5) for answer to your issue.
