### ISSUE TITLE
player is too tall.

### ISSUE THREAD

**Issue by MichaelJBrune** [Whimfoome/godot-FirstPersonStarter#11]
I love this template but one thing I had adjusted a lot of the times I used it is player height. The capsule is 1.5 meters in height and .6 in radius. Capsule height here isn't absolute height of the capsule but instead is a in this image: 
![image](https://user-images.githubusercontent.com/420072/111054231-e96cb400-841f-11eb-900f-e7eab2ed6903.png) 
thus the true height for a capsule is height + radius * 2. So the player capsule calculates to 2.7 meters or 8 feet 10 inches. Seems a bit tall for a typical person.

Is this the desired height?

**Comment by Whimfoome** [comment]
Thanks! I didn't have a certain height in mind when making the capsule, I just went with what felt right. Everyone is free to adjust it to what they want. In the future I might modify it to be something more reasonable with the real world. Thanks again for the explanation.

**Comment by Whimfoome** [comment]
Fixed in #13 The player is now 2 meters. Thanks again!
