### ISSUE TITLE
Not jumping from the ridge

### ISSUE THREAD

**Issue by theRanchkeeper** [Whimfoome/godot-FirstPersonStarter#16]
The player is not jumping from the ridges of platforms when space is pressed.
A Box collision shape as feet would fix it.

**Comment by Whimfoome** [comment]
Do you mean something like coyote timer? It's expected because this controller is not made for platformers, but you can fix this either by:
- Using Box Collider
- Implement coyote timer

**Comment by theRanchkeeper** [comment]
Oh ok I get it thanks and sorry for late reply
