### ISSUE TITLE
Rotation on start

### ISSUE THREAD

**Issue by deus369** [Whimfoome/godot-FirstPersonStarter#25]
Idk the best place to put this, but yeah. Add 'rot.y = get_owner().rotation.y' to the func _ready() inside the head script to fix starting rotation.

**Comment by Whimfoome** [comment]
I don't really understand what issue you are experiencing. If the Head node is child of the movementcontroller with zero rotation on x, y, z, which is local to the owner, there shouldn't be need in what you suggested.
