### ISSUE TITLE
godot 4

### ISSUE THREAD

**Issue by ghost** [Whimfoome/godot-FirstPersonStarter#26]
Hi

Can you also make a version for godot 4?

Thx

**Comment by Whimfoome** [comment]
Check out the godot4 branch

**Comment by ghost** [comment]
I'm a beginner and don't know any godot scripting but I downloaded the godot 4 version and opened it in godot 4 beta 17.
It doesn't run, this is the error:

Parser Error: Argument 1 of annotation "@export_node_path" isn't a constant expression.
Is it possible to update the code so it runs on latest godot 4?

![afbeelding](https://user-images.githubusercontent.com/122493908/216836991-6898e135-f937-4530-ba04-934e6a035d21.png)

**Comment by Whimfoome** [comment]
Try renaming it to `@export_node_path("Camera3D")`
(add the quotes)

`deg2rad()` -> `deg_to_rad()`

**Comment by ghost** [comment]
Could you maybe try it yourself and update the code on github?

I changed it but now another error :(
Where  are those errors coming from since it's the godot 4 version?
I added quotes there too and now it works!

![afbeelding](https://user-images.githubusercontent.com/122493908/217035529-b6f9b39c-81d9-4f41-ab71-5ad333990543.png)
