### ISSUE TITLE
keys not working

### ISSUE THREAD

**Issue by ghost** [Whimfoome/godot-FirstPersonStarter#27]
Hi

Several keys don't work.

The readme says

- Move with `W` `A` `S` `D` or `↑` `←` `↓` `→`
But the arrow keys don't work here, only `W` `A` `S` `D`  is working.

- Sprint with `Shift`
Shift doesn't work.

- Unlock/Lock Mouse with `Shift + F1`
Also not working.

Can you tell me how to fix it or is something missing?
I'm still learning scripting and using your example as a start.
Maybe you can update the code for latest godot 4 on github?

**Comment by Whimfoome** [comment]
Add them throught the Project Settings -> Input Map

**Comment by ghost** [comment]
Thanks, working! I thought the keys needed to be inside the code but I'm now slowly understanding how godot work.
