### ISSUE TITLE
fullscreen

### ISSUE THREAD

**Issue by ghost** [Whimfoome/godot-FirstPersonStarter#28]
Hi

Can you tell me what code I need to add and where to have a key that can switch from fullscreen to windowed mode and back?
I tried many codes I found online but nothing is working :(

**Comment by Whimfoome** [comment]
Sorry, but I am not a teacher or free support. You can always read the documentation of Godot or use google, here is the first result I got: https://godotengine.org/qa/28425/how-to-toggle-fullscreen-from-code
