### ISSUE TITLE
Movement keys don't work

### ISSUE THREAD

**Issue by EmeraldEelEntertainment** [Whimfoome/godot-FirstPersonStarter#3]
Hello. Your project caught my eye so I decided to try it out. However the WASD keys, nor the arrow keys, work in this project. I tried adding the WASD keys in the key inputs like ui_left, ui_right, etc. Still nothing. Since mouse_input isn't in the project once the files are imported I had to assign it myself.

I realize now, after inspecting the player controller script, that I need to add new key inputs: move_forward/backward/etc. I suppose it's not an issue in the end but the Github page doesn't make mention of this.

I'm new to Godot so forgive me if I'm missing anything. I added the inputs and now the demo scene works. Such a neat FPS controller, great stuff!

**Comment by Whimfoome** [comment]
If you import the whole template it should work by default. If you download only the player_controller script with the player itself you should add them manually. Thanks for pointing it out, I should write it in the readme. I'm glad you like it.

**Comment by Whimfoome** [comment]
Added a notice in the README.md file in [e94007b](https://github.com/Whimfoome/godot-FirstPersonStarter/commit/e94007be0043d433027f1721938671c1a4f19fac) commit.
