### ISSUE TITLE
Fix in the player acceleration and deceleration code

### ISSUE THREAD

**Issue by zSuperMicrowave** [Whimfoome/godot-FirstPersonStarter#32]
Sorry if this isn't written very well, it's my first time submitting an issue. I found out this project because I needed a template but I noticed a problem in the "MovementController.gd" code.

In that code there's this 58 line: "temp_vel = temp_vel.lerp(target, temp_accel * delta)"

When using the lerp function you need to keep in mind that the "weight" should be on the range of 0.0 to 1.0, otherwise the output will be outside the range of the starting value and the target value.

This means that, from my experience, the "weight" value must always be clamped between 0 and 1.

Even in delta is usually  a really small number, you just need to have your game lagging or to set a fast acceleration and the CharacterBody won't move correctly.

So a solution would be this:

"var clamped_accel = clamp(temp_accel * delta, 0.0, 1.0)
temp_vel = temp_vel.lerp(target, clamped_accel)"

I tested it, and it fixed the movement with an acceleration of "5318".
I didn't test it with lag.

**Comment by Whimfoome** [comment]
Oh, nice catch, Thanks!

If you would like you can open a pull request with the fix, or if you prefer not to, I can fix it, let me know!
