### ISSUE TITLE
Low performance in editor

### ISSUE THREAD

**Issue by Gamepro5** [Whimfoome/godot-FirstPersonStarter#5]
Thanks for making this, it's going to be very helpful, however, I noticed that unless I export it, it runs at 2 fps (despite it saying its 60+ on the top left) and almost crashes my operating system because other programs started lagging as well while I was testing this. I am using MacOS and because it exports and runs fine I assume it's an issue with the godot editor.

**Comment by Whimfoome** [comment]
Try to turn off SSAO in the environment settings, it is heavy to use if you don't have external graphics card.

**Comment by Gamepro5** [comment]
That was the issue and it is solved now. I don't get why it never affected exported projects but that does 100% solved. You're a god!
