### ISSUE TITLE
Deceleration is affected by slopes

### ISSUE THREAD

**Issue by Gamepro5** [Whimfoome/godot-FirstPersonStarter#8]
It's most noticeable on max steep slopes, but this simply means that if you are walking up it and then stop pressing that key you will slide down with deceleration before "stopping on slope". Most video games have you slide up the slope with deceleration (friction) as illogical as that sounds. This would also be consistent with the current behavior of moving up and down slopes at the same speed.

**Comment by TuxTheAstronaut** [comment]
i just made the deceleration have a higher value when on the ground so it would stop faster on slopes

**Comment by Gamepro5** [comment]
I've spent the last dozen months working on a fix for this. I had to start from scratch. https://github.com/Gamepro5/Custom_Kinematic_Physics

**Comment by Whimfoome** [comment]
In my testing, #13 seems to have fixed the issue, I will close this issue for now, if you still experience problems, which can be fixed without modifying the engine, feel free to open it again.
